### PR TITLE
cargo upgrade & update

### PR DESCRIPTION
**Pull request by pacman82**
dependencies automatically updated by running `cargo upgrade` and `cargo update`.

More can be done with minor refactorings. Let me know if this is good enough.

Cheers, Markus

### CODE REVIEW

**Comment by pacman82** [comment]
@sebastianneubauer

**Comment by pacman82** [comment]
added some slight bonus updates.

`cargo audit` comes back clean for me now. There is one warning of an unmaintained dependency of `criterion`. Which is the suite used for benchmarking.
That's of course irrelevant for production, but if it makes people nervous you can go on to delete the benchmarks and remove criterion from the suit.

**Review by steffen-schroeder-by — APPROVED** [review]
Thanks Markus, this is awesome. 🥳

**Comment by pacman82** [comment]
You are welcome,

@steffen-schroeder-by That 🍺 is still very much on my mind!

Cheers, Markus

**Pull request merged**
